[package]
name = "sha-hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hex-literal = "0.4.1"
rayon = "1.10.0"
sha2 = { version = "0.10.8", features = ["asm"] }

[profile.release]
debug = true
